postgresql: &postgresql
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: vins
  password:

development:
  <<: *postgresql
  # database: db/development.postgresql
  database: restaurant_development

test:
  <<: *postgresql
  # database: db/test.postgresql
  database: restaurant_test

production:
  <<: *postgresql
  # database: db/production.postgresql
  database: restaurant_production

